### ISSUE TITLE
reference to heatmap3d

### ISSUE THREAD

**Issue by morandd** [zcanter/aframe-scatterplot#6]
Hi,

If you like, maybe you can mention my recent component in your README:
https://github.com/morandd/aframe-heatmap3d/

Like yours, it is built for displaying spatial data. I'm reading data from an image file instead of JSON. (Once plus for using image files is the great compression: compare the filesize of the same data as JSON vs. a low-quality JPG.)

**Comment by zcanter** [comment]
Yeah sure sounds great! Thanks again for your work on this project. Aframe-Heatmap looks awesome as well!
